name: CI - Pruebas unitarias y commit

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar y ejecutar pruebas
        run: dotnet test

      