name: CI - Pruebas unitarias y commit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar y ejecutar pruebas
        run: dotnet test

      - name: Commit si las pruebas pasan
        if: success()
        uses: EndBug/add-and-commit@v2
        with:
          message: "Pruebas unitarias: OK"