name: Merge main

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - uses: actions/checkout@v2

      - name: Merge main
        if: ${{ needs.build.result == 'success' }}
        uses: actions/merge-pull-request@v4
        with:
          pull_request_number: ${{ github.event.pull_request.number }}
          merge_method: squash
          commit_message: "Merge branch 'main'"
